name: Validate JSON Schemas
on:
  pull_request:
    branches:
      - main
jobs:
  validate-schemas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate all json files using their own $schema properties
        uses: cardinalby/schema-validator-action@v3
        with:
          file: "demo/static/schemas/**/*.json"
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm ci
      - run: npm run lint
      - run: npm run gen-docs
      - run: npm run build
      - run: npm test
      - run: npm run validate-schemas
        working-directory: ./demo
